### ISSUE TITLE
router function options and resource versioning

### ISSUE THREAD

**Issue by macprog-guy** [tybenz/paper-router#1]
Hello,

Looking at the code it would seem that all router (get, post, resources...) functions take an options object as their last parameter, which can include things like a prefixRoute or a version. This is not what the README file suggests especially when considering versioning where the documentation passes the version as a third parameter instead of an object containing a version property. 

Also, lines 61 and 62 seem to be inverted. Line 61 uses the version variable whose value is computed in line 62 thus breaking versioning altogether (which might have been averted had there been versioning tests ;-).

So either I'm missing something basic, in which case I apologize and would like to be enlightened or we have a small issue in your otherwise very excellent module.

**Comment by tybenz** [comment]
Thanks for bringing this to my attention. I haven't been using the versioning feature in my recent projects, so it had slipped through the cracks. I've added tests for versioning support and updated the docs. You are correct. There should be parameters in the options argument, not extra arguments. I also swapped Line 61 & 62. Thanks for the heads-up. Let me know if you're still having issues or if the docs need tweaking.
