### ISSUE TITLE
How would authentication with Passport work?

### ISSUE THREAD

**Issue by ivancamilov** [tybenz/paper-router#2]
Hi! First of all thanks for this great module, it helps me organise my projects so well.

I was wondering if you could update the docs with an example of how to use an authentication middleware like Passport. I saw that `bindRoute` is supposed to take care of this, but I haven't been able to figure out how to do it yet.

Thanks!

**Comment by tybenz** [comment]
Thanks for the feedback! Glad you find it useful. I updated the docs: https://github.com/tybenz/paper-router#passport-authentication

Please let me know if it's clear/unclear and I can make changes.

**Comment by ivancamilov** [comment]
thanks! I think I'm a little lost here (I just recently started working with Node.js, being mostly a frontend dev) and I was trying to do the paper-router version of this:

```
router.route('/beers/:beer_id')
  .get(authController.isAuthenticated, beerController.getBeer)
  .put(authController.isAuthenticated, beerController.putBeer)
  .delete(authController.isAuthenticated, beerController.deleteBeer);
```

`isAuthenticated` is defined like this:

```
isAuthenticated = passport.authenticate('basic', { session : false });
```

I'm working with restify, not express, and I need to do the authentication using the `basic` strategy.

**Comment by tybenz** [comment]
Ok. Restify should be treated the same. I would put a before filter on each controller (the beer controller according to your example). `passport.authenticate` returns a middleware-type function, so use it to get the function, and then call it immediately, passing `req, res, next`

Something like this:

``` javascript
// controllers/beer.js
var BeerController = {
    before: [ name: 'isAuthenticated' ],

    isAuthenticated: function( req, res, next ) {
        passport.authenticate( 'basic', { session: false } )( req, res, next );
    },

    show: function( req, res, next ) {
        // ...
    }

    update: function( req, res, next ) {
        // ...
    }

    delete: function( req, res, next ) {
        // ...
    }
};
```

``` javascript
// routes.js
module.exports = function( router ) {
    router.resources( 'beer' );
};
```

**Comment by tybenz** [comment]
@ivancamilov Hope that helps. If you still have questions, let me know. Going to close this for now.

**Comment by ivancamilov** [comment]
Sorry I didn't reply earlier, I was on a short trip. I just tried this and it works perfectly! thanks a lot!! :smile:

**Comment by tybenz** [comment]
No prob. Let me know if you have any more questions.
